name: Update dictionaries

on:
  schedule:
    # At 00:00 (UTC) every day
    - cron: "0 0 * * *"

  # Allow to call the workflow manually
  workflow_dispatch:

jobs:
  # First job just to fill the pip cache
  warmup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements.txt

  dicthtml:
    runs-on: ubuntu-latest
    needs: [warmup]

    # List of locales to generate
    # Sorted by the number of words
    strategy:
      matrix:
        locale:
          - fr
          - en
          - de
          - es
          - el
          - pt
          - sv
          - it
          - ca
          # - ru
          - no

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements.txt

      - name: Download the latest Wiktionary dump
        run: python -Wd -m wikidict ${{ matrix.locale }} --download

      - name: Parse the dump
        run: python -Wd -m wikidict ${{ matrix.locale }} --parse

      - name: Render templates
        run: python -Wd -m wikidict ${{ matrix.locale }} --render

      - name: Convert to dictionaries
        run: python -Wd -m wikidict ${{ matrix.locale }} --convert

      - name: Upload the dictionary (DictFile)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: data/${{ matrix.locale }}/dict-${{ matrix.locale }}-${{ matrix.locale }}*.df.bz2
          tag: ${{ matrix.locale }}
          overwrite: true
          file_glob: true

      - name: Upload the dictionary (Kobo)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: data/${{ matrix.locale }}/dicthtml-${{ matrix.locale }}-${{ matrix.locale }}*.zip
          tag: ${{ matrix.locale }}
          overwrite: true
          file_glob: true

      - name: Upload the dictionary (StarDict)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: data/${{ matrix.locale }}/dict-${{ matrix.locale }}-${{ matrix.locale }}*.zip
          tag: ${{ matrix.locale }}
          overwrite: true
          file_glob: true

      - name: Update the release description
        run: python -Wd -m wikidict ${{ matrix.locale }} --update-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
