name: Unit tests

on: pull_request

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-tests.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-tests') }}
    - name: Install requirements
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-tests.txt
    - name: Unit tests (doctests + common + fr)
      run: python -Wd -m pytest -vv tests/*.py tests/fr --doctest-modules scripts
    - name: Test the user functions documentation
      run: |
        pydocstyle scripts/user_functions.py
        pdoc --html --force scripts.user_functions
        pdoc scripts.user_functions
