name: Unit tests

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install LaTeX
        run: |
          /bin/bash -c "$(curl -sL https://git.io/vokNn)"
          sudo apt-fast update
          sudo apt-fast --yes install dvipng texlive-fonts-extra texlive-latex-extra texlive-science
        env:
          DEBIAN_FRONTEND: noninteractive

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt', 'requirements-tests.txt') }}

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements-tests.txt

      - name: Unit tests
        run: python -Wd -m pytest tests --doctest-modules wikidict

      - name: Generate the user functions documentation
        run: |
          pydocstyle wikidict/user_functions.py
          pdoc --html --force wikidict.user_functions

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: user_functions.html
          path: html/wikidict/user_functions.html
