name: Quality & Tests

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt', 'requirements-tests.txt') }}

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements-tests.txt

      - name: Style
        run: python -m black --check --diff wikidict tests

      - name: Lint
        run: python -m flake8 wikidict tests

      - name: Types
        run: python -m mypy wikidict

      - name: Unit tests
        run: python -Wd -m pytest tests --doctest-modules wikidict

      - name: Automerge
        if: github.actor == 'dependabot[bot]'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge,!DO_NOT_MERGE
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
