name: Quality & Tests

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install requirements
        run: python -m pip install -r requirements-tests.txt

      - name: Quality checks, and linters
        run: ./check.sh

      - name: Unit tests
        run: python -Wd -m pytest tests --doctest-modules wikidict

      - name: Automerge
        if: github.actor == 'dependabot[bot]'
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automerge,!DO_NOT_MERGE
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
