name: Unit tests (macOS)

on: pull_request

jobs:
  tests:
    name: Run tests for ${{ matrix.os }} for ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"

      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt', 'requirements-tests.txt') }}

      - name: Install requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: python -m pip install -r requirements-tests.txt

      - name: Unit tests
        run: python -Wd -m pytest tests/test_0_download.py tests/test_1_parse.py tests/test_2_render.py tests/test_3_convert.py
