name: Unit tests

on: pull_request

jobs:
  job:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8

    - name: Install LaTeX requirements
      run: sudo apt install dvipng texlive-latex-extra

    - uses: actions/cache@v2.1.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-tests.txt') }}
        restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-tests') }}

    - name: Install requirements
      run: python -m pip install -r requirements-tests.txt

    - name: Unit tests
      run: python -Wd -m pytest tests --doctest-modules scripts

    - name: Generate the user functions documentation
      run: |
        pydocstyle scripts/user_functions.py
        pdoc --html --force scripts.user_functions

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: user_functions.html
        path: html/scripts/user_functions.html
